classification: storage
color: cardboard
description_extra: ''
description_main: 51_mm_width_112_mm_height_301_mm_depth
id: storage_box_warehouse_cardboard_51_mm_width_112_mm_height_301_mm_depth_rajapack_rbac11
manufacturer: rajapack
part_number: rbac11
size: ''
type: box_warehouse
