classification: storage
color: cardboard
description_extra: ''
description_main: 101_mm_width_112_mm_height_301_mm_depth
id: storage_box_warehouse_cardboard_101_mm_width_112_mm_height_301_mm_depth_rajapack_rbac12
manufacturer: rajapack
part_number: rbac12
size: ''
type: box_warehouse
