classification: storage
color: cardboard
description_extra: ''
description_main: 122_mm_width_110_mm_height_175_mm_depth
id: storage_box_warehouse_cardboard_122_mm_width_110_mm_height_175_mm_depth_oomlout_box_1
manufacturer: oomlout
part_number: box_1
size: ''
type: box_warehouse
