classification: storage
color: cardboard
description_extra: ''
description_main: 201_mm_width_112_mm_height_301_mm_depth
id: storage_box_warehouse_cardboard_201_mm_width_112_mm_height_301_mm_depth_rajapack_rbac14
manufacturer: rajapack
part_number: rbac14
size: ''
type: box_warehouse
