classification: storage
color: black
description_extra: ''
description_main: 736_mm_width_990_mm_height_70_litre_capacity
id: storage_bin_bag_60_micron_thickness_black_736_mm_width_990_mm_height_70_litre_capacity_kite_packaging_rs240_182939
manufacturer: kite_packaging
part_number: rs240_182939
size: 60_micron_thickness
type: bin_bag
