classification: storage
color: cardboard
description_extra: ''
description_main: 151_mm_width_112_mm_height_401_mm_depth
id: storage_box_warehouse_cardboard_151_mm_width_112_mm_height_401_mm_depth_rajapack_rbac16
manufacturer: rajapack
part_number: rbac16
size: ''
type: box_warehouse
