classification: storage
color: ''
description_extra: ''
description_main: 190_mm_width_150_mm_height_260_mm_depth
id: storage_box_warehouse_sockerbit_190_mm_width_150_mm_height_260_mm_depth_ikea_503_161_82
manufacturer: ikea
part_number: '503_161_82'
size: sockerbit
type: box_warehouse
