classification: storage
color: black
description_extra: wheelie_bin_liner
description_main: 700_mm_width_1070_mm_height_70_litre_capacity
id: storage_bin_bag_50_micron_thickness_black_700_mm_width_1070_mm_height_70_litre_capacity_wheelie_bin_liner_rajapack_bprs7050
manufacturer: rajapack
part_number: bprs7050
size: 50_micron_thickness
type: bin_bag
